platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'E-CANE' do
 
  # Pods for Cane_App
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'



  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'


   pod 'SwiftyJSON', '5.0'      
   pod 'Charts', '3.3.0'  

     pod 'Firebase/Analytics'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'

  target 'E-CANETests' do
    inherit! :search_paths
    # Pods for testing


    pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

    post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
   config.build_settings['SWIFT_VERSION'] = '5'
   end
  end
end

  use_native_modules!
end

target 'E-CANE-tvOS' do
  # Pods for Cane_App-tvOS

  target 'E-CANE-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
